sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kunwarf/work-flow -f Dockerfile .

#script:
 #- docker run -e CI=true kunwarf/work-flow npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "work-flow"
  env: "Work-flow-env"
  bucket_name: "elasticbeanstalk-us-east-1-133903928003"
  bucket_path: "work-flow"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"